image:
  repository: us-central1-docker.pkg.dev/pisces-12/pisces-repo/pisces-gateway
  pullPolicy: Always

serviceAccountName: pisces-gateway-ksa

env:
  REDIS_ADDR: "10.73.104.43:6379"
  LOGGING_LEVEL: "DEBUG"