image:
  repository: us-central1-docker.pkg.dev/pisces-12/pisces-repo/pisces-gateway
  pullPolicy: Always

serviceAccountName: pisces-gateway-ksa

env:
  LOGGING_LEVEL: "DEBUG"
  FRASIER_BOT_URL: "http://frasier-chat-svc"

gemini:
  project: "pisces-12"
  location: "us-central1"
  model: "gemini-2.5-flash"
  embedding_model: "gemini-embedding-001"
