apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          env:
            - name: REDIS_ADDR
              value: "pisces-gateway-redis-svc:6379"
            - name: LOGGING_LEVEL
              value: {{ .Values.env.LOGGING_LEVEL | quote }}
            - name: FRASIER_BOT_URL
              value: {{ .Values.env.FRASIER_BOT_URL | quote }}
            - name: GEMINI_PROJECT
              value: {{ .Values.gemini.project | quote }}
            - name: GEMINI_LOCATION
              value: {{ .Values.gemini.location | quote }}
            - name: GEMINI_MODEL
              value: {{ .Values.gemini.model | quote }}            
            - name: EMBEDDING_MODEL
              value: {{ .Values.gemini.embedding_model | quote }}