apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # 5GB of persistent disk space
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
spec:
  replicas: 1
  # Strategy: Recreate ensures the old pod releases the disk before the new pod attaches to it
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
      - name: redis
        image: redis/redis-stack-server:latest
        ports:
        - containerPort: 6379
        # 1. Tell the container where to mount the disk internally
        volumeMounts:
        - name: redis-storage
          mountPath: /data 
      # 2. Tell the Pod which PVC to use as the physical disk
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-svc
spec:
  selector:
    app: {{ .Release.Name }}-redis
  ports:
  - port: 6379
    targetPort: 6379