apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: default
  annotations:
    # This officially bridges the Kubernetes pod to your GCP permissions!
    iam.gke.io/gcp-service-account: "pisces-gateway-sa@pisces-12.iam.gserviceaccount.com"